# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff21ec6daf519c1abf7466a4ef3f12f9edaed025aa6515258f7503b52010ff01d41752b254d7c539e9bab9595fdd9bdd010afb72ac451640399d396f70540e8

test:
  secret_key_base: d90e7d26f1167765525f01a0da649b61052c19d8bd972b59243744d3646e84dd6356d23212b048b9a898f8fe115567f4d8bef5c939c1bc6f672d289041308ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
